version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"

  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Composer"
    labels:
      - "composer"
      - "dependencies"
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: "/"
